// End-to-end check of the wallet, driven through a real browser.
// Tests verify that offline banking buttons are disabled with descriptive labels
// Starts its own static server on a free port and uses whichever Chromium
// Playwright installed, so it runs the same on a laptop and in CI.
const http = require('http');
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const jsQRmod = require('jsqr');
const jsQR = jsQRmod.default || jsQRmod;

const ROOT = __dirname;
const TYPES = {
  '.html': 'text/html', '.js': 'text/javascript', '.svg': 'image/svg+xml',
  '.webmanifest': 'application/manifest+json', '.json': 'application/json',
};

function serve() {
  const server = http.createServer((req, res) => {
    const rel = decodeURIComponent(req.url.split('?')[0]).replace(/^\/+/, '') || 'index.html';
    const file = path.join(ROOT, rel);
    if (!file.startsWith(ROOT) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      res.writeHead(404).end('not found');
      return;
    }
    res.writeHead(200, { 'content-type': TYPES[path.extname(file)] || 'application/octet-stream' });
    fs.createReadStream(file).pipe(res);
  });
  return new Promise(r => server.listen(0, '127.0.0.1', () => r(server)));
}

let bad = 0;
const ok = (l, c, extra = '') => { if (!c) bad++; console.log(`${c ? 'ok  ' : 'FAIL'}  ${l}${extra ? '  ' + extra : ''}`); };

(async () => {
  const server = await serve();
  const base = `http://127.0.0.1:${server.address().port}`;
  // CI installs Playwright's own Chromium; CHROME_PATH lets a sandbox point at one it already has.
  const b = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
  const p = await b.newPage({ viewport: { width: 390, height: 844 } }); // a phone
  const errs = [];
  p.on('pageerror', e => errs.push(e.message));
  await p.goto(`${base}/index.html`);
  await p.waitForTimeout(600);

  // a real payee address, generated by the reference SDK
  const payee = require('@stellar/stellar-sdk').Keypair.random().publicKey();

  ok('starts with no key and no pay form', await p.isVisible('#mkdev') && !(await p.isVisible('#payform')));

  await p.click('#mkdev');
  await p.waitForTimeout(400);
  ok('creating a key reveals the pay form', await p.isVisible('#payform'));

  await p.fill('#payee', payee);
  await p.fill('#amount', '2.5');
  await p.click('#signbtn');
  await p.waitForTimeout(500);
  const code = await p.inputValue('#code');
  ok('signing produces a 246-character voucher', code.length === 246, `got ${code.length}`);
  const summary = await p.textContent('#paysummary');
  ok('the summary shows the right amount', summary.includes('2.5 XLM'), summary.trim());

  // the payee accepts it
  await p.click('nav button[data-v=recv]');
  await p.fill('#inp', code);
  await p.click('#check');
  await p.waitForTimeout(500);
  let res = await p.textContent('#result');
  ok('a good voucher verifies offline', res.includes('signature checks out'));
  ok('and shows the amount', res.includes('2.5 XLM'));
  await p.click('#result button');
  await p.waitForTimeout(400);
  ok('accepting moves it to the wallet', (await p.textContent('#pending')).includes('2.5 XLM'));

  // tampering must be caught
  await p.click('nav button[data-v=recv]');
  const tampered = code.slice(0, 100) + (code[100] === 'A' ? 'B' : 'A') + code.slice(101);
  await p.fill('#inp', tampered);
  await p.click('#check');
  await p.waitForTimeout(500);
  res = await p.textContent('#result');
  ok('a tampered voucher is refused', res.includes('altered'), res.trim().slice(0, 60));

  // rubbish input must not explode
  await p.fill('#inp', 'hello');
  await p.click('#check');
  await p.waitForTimeout(300);
  ok('rubbish input gives a message, not a crash', (await p.textContent('#result')).includes('voucher code'));

  // a mistyped address must be caught before signing
  await p.click('nav button[data-v=pay]');
  await p.fill('#payee', 'G' + 'A'.repeat(55));
  await p.fill('#amount', '1');
  await p.click('#signbtn');
  await p.waitForTimeout(400);
  ok('a mistyped address is caught', (await p.textContent('#paysummary')).includes('typo'));

  // the key survives a reload, like a real wallet
  await p.reload();
  await p.waitForTimeout(700);
  ok('the device key survives a reload', await p.isVisible('#payform'));

  // offline is the whole point
  await p.context().setOffline(true);
  await p.reload();
  await p.waitForTimeout(900);
  ok('the app still loads with the network off', await p.isVisible('#payform'));
  await p.fill('#payee', payee);
  await p.fill('#amount', '0.75');
  await p.click('#signbtn');
  await p.waitForTimeout(500);
  ok('and can still sign offline', (await p.inputValue('#code')).length === 246);
  await p.context().setOffline(false);

  // ---- the QR code has to actually scan, not merely appear ----
  await p.click('nav button[data-v=pay]');
  await p.fill('#payee', payee);
  await p.fill('#amount', '3.25');
  await p.click('#signbtn');
  await p.waitForTimeout(500);
  const shown = await p.inputValue('#code');
  ok('a QR code is drawn for the voucher', await p.isVisible('#qr svg'));

  // Pull the matrix the page itself produced and put it through a real decoder.
  const matrix = await p.evaluate(async (code) => {
    const { encodeQR } = await import('./qr.js');
    const { size, modules } = encodeQR(code);
    return { size, rows: modules.map((r) => Array.from(r)) };
  }, shown);
  const scale = 3, quiet = 4, dim = (matrix.size + quiet * 2) * scale;
  const px = new Uint8ClampedArray(dim * dim * 4).fill(255);
  for (let r = 0; r < matrix.size; r++)
    for (let c = 0; c < matrix.size; c++) {
      if (!matrix.rows[r][c]) continue;
      for (let dy = 0; dy < scale; dy++)
        for (let dx = 0; dx < scale; dx++) {
          const i = (((r + quiet) * scale + dy) * dim + (c + quiet) * scale + dx) * 4;
          px[i] = px[i + 1] = px[i + 2] = 0;
        }
    }
  const decoded = jsQR(px, dim, dim);
  ok('the QR the browser drew decodes back to the voucher', decoded && decoded.data === shown,
     decoded ? (decoded.data === shown ? '' : 'decoded something else') : 'decoded nothing');

  ok('the code text is hidden behind a button, not dumped on screen',
     await p.isHidden('#code') && await p.isVisible('#showcode'));
  await p.click('#showcode');
  await p.waitForTimeout(200);
  ok('and can be shown when someone needs to copy it', await p.isVisible('#code'));

  // ---- the signing key must not be readable ----
  const leaked = await p.evaluate(() => {
    const out = [];
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      out.push([k, localStorage.getItem(k)]);
    }
    return out;
  });
  const looksLikeAKey = leaked.some(([, v]) => /"seed"|[0-9a-f]{64}/.test(v || ''));
  ok('no private key material is left in localStorage', !looksLikeAKey,
     looksLikeAKey ? JSON.stringify(leaked).slice(0, 120) : '');

  const stored = await p.evaluate(async () => {
    const { loadDevice } = await import('./store.js');
    const d = await loadDevice();
    if (!d) return { found: false };
    let exported = 'refused';
    try {
      await crypto.subtle.exportKey('pkcs8', d.key);
      exported = 'HANDED IT OVER';
    } catch { /* good */ }
    return { found: true, type: d.key.type, extractable: d.key.extractable, exported };
  });
  ok('the key is stored as a CryptoKey, not bytes', stored.found && stored.type === 'private');
  ok('and the browser refuses to export it',
     stored.extractable === false && stored.exported === 'refused', JSON.stringify(stored));

  // ---- a key from the old version gets moved, not abandoned ----
  await p.evaluate(async () => {
    const { forgetDevice } = await import('./store.js');
    await forgetDevice();
    // 32 bytes of seed, exactly as the previous version wrote it.
    const seed = '11'.repeat(32);
    const pkcs8 = new Uint8Array([
      0x30,0x2e,0x02,0x01,0x00,0x30,0x05,0x06,0x03,0x2b,0x65,0x70,0x04,0x22,0x04,0x20,
      ...seed.match(/../g).map((h) => parseInt(h, 16)),
    ]);
    const k = await crypto.subtle.importKey('pkcs8', pkcs8, { name: 'Ed25519' }, true, ['sign']);
    const jwk = await crypto.subtle.exportKey('jwk', k);
    const pub = atob(jwk.x.replace(/-/g, '+').replace(/_/g, '/'));
    const pubHex = Array.from(pub, (c) => c.charCodeAt(0).toString(16).padStart(2, '0')).join('');
    localStorage.setItem('lastmile.device.v1', JSON.stringify({ seed, pub: pubHex }));
  });
  await p.reload();
  await p.waitForTimeout(900);
  ok('an old localStorage key still opens the wallet', await p.isVisible('#payform'));
  const migrated = await p.evaluate(async () => {
    const { loadDevice } = await import('./store.js');
    const d = await loadDevice();
    return { moved: !!d, extractable: d ? d.key.extractable : null,
             legacyGone: localStorage.getItem('lastmile.device.v1') === null };
  });
  ok('it is moved into protected storage', migrated.moved && migrated.extractable === false);
  ok('and the readable copy is wiped', migrated.legacyGone);

  // ---- banking ----
  // The relayer is stubbed: this is about what the wallet does with each answer,
  // not about the chain, which the contract repo proves against live testnet.
  // Start from an empty wallet so the voucher under test is index 0 and the
  // assertions below are about the one we just made, not one left over.
  await p.evaluate(() => localStorage.removeItem('lastmile.accepted.v1'));
  await p.reload();
  await p.waitForTimeout(700);
  await p.click('nav button[data-v=pay]');
  await p.fill('#payee', payee);
  await p.fill('#amount', '1.5');
  await p.click('#signbtn');
  await p.waitForTimeout(400);
  const toBank = await p.inputValue('#code');
  await p.click('nav button[data-v=recv]');
  await p.fill('#inp', toBank);
  await p.click('#check');
  await p.waitForTimeout(400);
  await p.click('#result button');
  await p.waitForTimeout(400);
  ok('an accepted voucher shows as not yet banked',
     (await p.textContent('#pending')).includes('not yet banked'));

  let sentBody = null;
  await p.route('**/api/redeem', async (route) => {
    sentBody = route.request().postDataJSON();
    await route.fulfill({
      status: 409,
      contentType: 'application/json',
      body: JSON.stringify({ error: 'this nonce has already been redeemed', code: 6 }),
    });
  });
  await p.click('[data-bank="0"]');
  await p.waitForTimeout(600);
  ok('banking sends the voucher to the relayer', sentBody && sentBody.code === toBank);
  let wallet = await p.textContent('#pending');
  ok("the contract's refusal is shown in its own words",
     wallet.includes('already been redeemed'), wallet.replace(/\s+/g, ' ').slice(0, 90));
  ok('and the voucher can be retried', await p.isVisible('[data-bank="0"]'));

  await p.unroute('**/api/redeem');
  await p.route('**/api/redeem', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ hash: 'abc123def4567890', ledger: 42, amount: '15000000' }),
    }));
  await p.click('[data-bank="0"]');
  await p.waitForTimeout(600);
  wallet = await p.textContent('#pending');
  ok('a successful bank shows the ledger it landed in', wallet.includes('ledger 42'), wallet.replace(/\s+/g, ' ').slice(0, 90));
  ok('and stops offering to bank it again', !(await p.isVisible('[data-bank="0"]')));

  await p.reload();
  await p.waitForTimeout(800);
  await p.click('nav button[data-v=wallet]');
  await p.waitForTimeout(300);
  ok('banked stays banked across a reload', (await p.textContent('#pending')).includes('banked'));

  // Offline, banking must not pretend.
  await p.context().setOffline(true);
  await p.evaluate(() => dispatchEvent(new Event('offline')));
  await p.waitForTimeout(300);
  await p.click('nav button[data-v=pay]');
  await p.fill('#payee', payee);
  await p.fill('#amount', '0.5');
  await p.click('#signbtn');
  await p.waitForTimeout(400);
  const off = await p.inputValue('#code');
  await p.click('nav button[data-v=recv]');
  await p.fill('#inp', off);
  await p.click('#check');
  await p.waitForTimeout(400);
  await p.click('#result button');
  await p.waitForTimeout(400);
  const offText = await p.textContent('#pending');
  ok('with no signal the wallet says banking needs a connection',
     offText.includes('needs a connection'), offText.replace(/\s+/g, ' ').slice(0, 90));
  await p.context().setOffline(false);

  // ---- the cash desk ----
  // An agent behind a counter: set a rate once, and every screen that shows an
  // amount also shows the cash to hand over. None of it needs a network.
  await p.context().setOffline(true);
  await p.evaluate(() => dispatchEvent(new Event('offline')));
  await p.click('nav button[data-v=wallet]');
  await p.waitForTimeout(300);

  ok('the desk is off until a rate is set',
     (await p.textContent('#deskstate')).includes('Set a rate'));

  await p.selectOption('#cur', 'NGN');
  await p.fill('#rate', '1600');
  await p.fill('#fee', '2');
  await p.click('#savedesk');
  await p.waitForTimeout(300);
  let state = await p.textContent('#deskstate');
  ok('saving a rate opens the desk', state.includes('₦1,600.00') && state.includes('2%'), state.trim());

  await p.click('nav button[data-v=pay]');
  await p.fill('#payee', payee);
  await p.fill('#amount', '2.5');
  await p.waitForTimeout(300);
  let cash = await p.textContent('#paycash');
  // 2.5 XLM at ₦1,600 is ₦4,000, less a 2% fee, so ₦3,920 changes hands.
  ok('the pay screen says what cash to hand over',
     cash.includes('₦3,920.00') && cash.includes('₦80.00'), cash.trim());

  await p.fill('#amount', 'nonsense');
  await p.waitForTimeout(200);
  ok('a nonsense amount shows no cash figure rather than a wrong one',
     await p.isHidden('#paycash'));
  await p.fill('#amount', '2.5');
  await p.waitForTimeout(200);

  // A voucher arriving at the counter must say the same number.
  await p.click('#signbtn');
  await p.waitForTimeout(500);
  const deskCode = await p.inputValue('#code');
  await p.click('nav button[data-v=recv]');
  await p.fill('#inp', deskCode);
  await p.click('#check');
  await p.waitForTimeout(500);
  const res2 = await p.textContent('#result');
  ok('the accept screen agrees on the cash', res2.includes('₦3,920.00'), res2.replace(/\s+/g, ' ').slice(0, 80));
  ok('and the button says what is about to happen',
     (await p.textContent('#result button')).includes('hand over the cash'));

  await p.click('#result button');
  await p.waitForTimeout(500);
  const trades = await p.textContent('#trades');
  ok('the trade is written to the cash log',
     trades.includes('2.5 XLM') && trades.includes('₦3,920.00'), trades.replace(/\s+/g, ' ').slice(0, 70));

  await p.reload();
  await p.waitForTimeout(800);
  await p.click('nav button[data-v=wallet]');
  await p.waitForTimeout(300);
  ok('the desk and the log survive a reload',
     (await p.textContent('#deskstate')).includes('₦1,600.00') &&
     (await p.textContent('#trades')).includes('₦3,920.00'));

  ok('with no signal the float cannot be checked, and says so',
     (await p.textContent('#checkfloat')).includes('needs a connection'));
  ok('and an unchecked float is flagged rather than shown as zero',
     (await p.textContent('#floatamt')).trim() === '—' &&
     (await p.textContent('#floatwhen')).includes('never checked'));

  // ---- getting paid without anyone typing an address ----
  const myAddr = (await p.textContent('#myaddr')).trim();
  ok('the wallet shows its own address', /^G[A-Z2-7]{55}$/.test(myAddr), myAddr.slice(0, 12));
  ok('and draws it as a code', await p.isVisible('#myqr svg'));

  const sep7 = await p.evaluate(async () => {
    const { payUri, readAddress } = await import('./cash.js');
    const { encodeQR } = await import('./qr.js');
    const g = document.getElementById('myaddr').textContent.trim();
    const uri = payUri({ destination: g });
    const { size, modules } = encodeQR(uri);
    return { uri, back: readAddress(uri), size, rows: modules.map((r) => Array.from(r)) };
  });
  ok('the code is a SEP-7 payment request other wallets can read',
     sep7.uri.startsWith('web+stellar:pay?destination=G') && sep7.back.address === myAddr);

  {
    const scale = 3, quiet = 4, dim = (sep7.size + quiet * 2) * scale;
    const px = new Uint8ClampedArray(dim * dim * 4).fill(255);
    for (let r = 0; r < sep7.size; r++)
      for (let c = 0; c < sep7.size; c++) {
        if (!sep7.rows[r][c]) continue;
        for (let dy = 0; dy < scale; dy++)
          for (let dx = 0; dx < scale; dx++) {
            const i = (((r + quiet) * scale + dy) * dim + (c + quiet) * scale + dx) * 4;
            px[i] = px[i + 1] = px[i + 2] = 0;
          }
      }
    const got = jsQR(px, dim, dim);
    ok('and it scans back to the same address',
       got && got.data === sep7.uri, got ? 'decoded' : 'decoded nothing');
  }

  const scanned = await p.evaluate(async (g) => {
    const { readAddress, payUri } = await import('./cash.js');
    return {
      bare: readAddress(g)?.address,
      lower: readAddress(g.toLowerCase())?.address,
      uri: readAddress(payUri({ destination: g, amount: '7' })),
      junk: readAddress('just some text'),
    };
  }, myAddr);
  ok('a scanned address is accepted bare, in lower case, or as SEP-7',
     scanned.bare === myAddr && scanned.lower === myAddr && scanned.uri.address === myAddr &&
     scanned.uri.amount === '7' && scanned.junk === null);

  await p.click('#cleardesk');
  await p.waitForTimeout(300);
  ok('the desk can be turned off again',
     (await p.textContent('#deskstate')).includes('Set a rate'));
  await p.click('nav button[data-v=pay]');
  await p.waitForTimeout(200);
  ok('and the cash line goes with it', await p.isHidden('#paycash'));
  await p.context().setOffline(false);


  // ---------------------------------------------------------------- the ramp
  //
  // The wallet cannot read a SEP-10 challenge -- no XDR decoder, and it is not
  // getting one. It signs a hash the relayer hands it, and the only thing
  // standing between that and blind signing is a check that the anchor signed
  // those exact bytes. So the interesting test is not "does cash-in work". It is
  // "can a relayer that has been got at get a signature out of this wallet".

  const { Keypair } = require('@stellar/stellar-sdk');
  const anchorKp = Keypair.random();
  const impostorKp = Keypair.random();

  const TOML = `
VERSION="2.0.0"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
SIGNING_KEY="${anchorKp.publicKey()}"
WEB_AUTH_ENDPOINT="https://anchor.test/auth"
TRANSFER_SERVER_SEP0024="https://anchor.test/sep24"
`;

  // A relayer under our control, so each way it could misbehave can be tried.
  let relayer = { signingKey: anchorKp.publicKey(), signWith: anchorKp };
  let tokenCalls = 0;

  // SEP-1 requires stellar.toml to be CORS-readable, which is the only reason a
  // browser can check the anchor's identity for itself. Serve it the same way.
  await p.route('**/.well-known/stellar.toml', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'text/plain',
      headers: { 'access-control-allow-origin': '*' },
      body: TOML,
    }));

  await p.route('**/api/anchor', async (route) => {
    const body = JSON.parse(route.request().postData());
    const send = (o) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(o) });
    if (body.action === 'connect') {
      return send({
        signingKey: relayer.signingKey,
        networkPassphrase: 'Test SDF Network ; September 2015',
        deposit: { USDC: { enabled: true, min_amount: 1, max_amount: 500 }, SRT: { enabled: false } },
        withdraw: { USDC: { enabled: true } },
        currencies: [{ code: 'USDC' }],
      });
    }
    if (body.action === 'challenge') {
      const hash = require('crypto').randomBytes(32);
      // Keypair.sign returns a Uint8Array in stellar-sdk 17, and
      // Uint8Array.toString('hex') is "147,211,34,..." with no complaint. The
      // first version of this test did exactly that, and the forged-challenge
      // check below passed because *every* signature was unreadable -- which is
      // a test that proves nothing while looking like it proves everything.
      const sign = (kp, msg) => Buffer.from(kp.sign(msg)).toString('hex');
      return send({
        transaction: 'AAAA-pretend',
        networkPassphrase: 'Test SDF Network ; September 2015',
        hash: hash.toString('hex'),
        anchorSignature: sign(relayer.signWith, hash),
        account: body.account,
      });
    }
    if (body.action === 'token') { tokenCalls++; return send({ token: 'jwt.for.you' }); }
    if (body.action === 'start') return send({ url: 'https://anchor.test/i/abc', id: 'tx-1' });
    if (body.action === 'status') return send({ transaction: { id: 'tx-1', status: 'pending_user_transfer_start' } });
    return route.fulfill({ status: 400, body: '{"error":"no"}' });
  });

  await p.click('nav button[data-v=ramp]');
  await p.waitForTimeout(200);
  ok('the ramp screen is reachable', await p.isVisible('#anchordom'));
  ok('and nothing is offered before an anchor is chosen', await p.isHidden('#rampform'));

  await p.fill('#anchordom', 'anchor.test');
  await p.click('#anchorgo');
  await p.waitForTimeout(500);
  ok('connecting shows the key read from the anchor itself',
     (await p.textContent('#anchorkey')) === anchorKp.publicKey(),
     await p.textContent('#anchorerr'));
  ok('and the ramp opens', await p.isVisible('#rampform'));

  const assets = await p.$$eval('#rampasset option', (os) => os.map((o) => o.value));
  ok('only assets the anchor actually takes are offered',
     assets.length === 1 && assets[0] === 'USDC', assets.join(','));
  ok('the published limits are shown',
     (await p.textContent('#ramplimits')).includes('at least 1'));

  // The attack. The relayer keeps a real-looking flow but signs the challenge
  // with a key that is not the anchor's.
  relayer = { signingKey: anchorKp.publicKey(), signWith: impostorKp };
  tokenCalls = 0;
  await p.fill('#rampamt', '25');
  await p.click('#rampgo');
  await p.waitForTimeout(700);
  ok('a forged challenge is refused',
     (await p.textContent('#ramperr')).includes('has not signed the challenge'));
  ok('and nothing was signed or sent', tokenCalls === 0);
  ok('and no job is recorded for it', await p.isHidden('#rampjobs'));

  // The relayer lying about who the anchor is, which the wallet can catch
  // because it read stellar.toml for itself.
  relayer = { signingKey: impostorKp.publicKey(), signWith: anchorKp };
  await p.click('#anchorgo');
  await p.waitForTimeout(500);
  ok('a relayer that reports a different signing key is stopped',
     (await p.textContent('#anchorerr')).includes('Stopping here'));

  // And now the honest case.
  relayer = { signingKey: anchorKp.publicKey(), signWith: anchorKp };
  await p.click('#anchorgo');
  await p.waitForTimeout(500);
  await p.fill('#rampamt', '25');
  await p.click('#rampgo');
  await p.waitForTimeout(800);
  ok('an honest anchor gets a signature and a session', tokenCalls === 1, await p.textContent('#ramperr'));
  ok('the deposit shows up in flight', await p.isVisible('#rampjobs'));
  const job = await p.textContent('#rampqueue');
  ok('and says what the anchor is waiting for, in words',
     job.includes('Cash in') && job.includes('25 USDC'), job.replace(/\s+/g, ' ').slice(0, 90));
  // A template literal will happily print "[object Object]" and call it a day.
  ok('with no object stringified into the page', !job.includes('[object'), job.replace(/\s+/g, ' ').slice(0, 90));

  await p.click('#ramprefresh');
  await p.waitForTimeout(600);
  ok('checking again reports the status in plain language',
     (await p.textContent('#rampqueue')).includes('Waiting for you to send the money'));

  await p.reload();
  await p.waitForTimeout(700);
  await p.click('nav button[data-v=ramp]');
  await p.waitForTimeout(200);
  ok('the job survives a reload', (await p.textContent('#rampqueue')).includes('Cash in'));
  ok('and the anchor domain is remembered',
     (await p.inputValue('#anchordom')) === 'anchor.test');

  // A reload does not keep the binding, and should not: the anchor's signing key
  // has to be read fresh before anything is signed against it.
  ok('but the ramp stays shut until the anchor is checked again', await p.isHidden('#rampform'));

  await p.click('#anchorgo');
  await p.waitForTimeout(500);
  await p.click('#wdrbtn');
  await p.waitForTimeout(200);
  const outAssets = await p.$$eval('#rampasset option', (os) => os.map((o) => o.value));
  ok('cash out offers what the anchor pays out, not what it takes in',
     outAssets.length === 1 && outAssets[0] === 'USDC', outAssets.join(','));
  ok('and its limits are whatever that side publishes',
     (await p.textContent('#ramplimits')) === 'No limits published.',
     await p.textContent('#ramplimits'));

  await p.unroute('**/api/anchor');
  await p.unroute('**/.well-known/stellar.toml');

  ok('no uncaught page errors', errs.length === 0, errs.join(' | '));
  await b.close();
  server.close();
  console.log(bad ? `\n${bad} FAILURES` : '\nTHE WALLET WORKS, INCLUDING OFFLINE');
  process.exit(bad ? 1 : 0);
})();
